audit/ProfApp/urls.py
from django.urls import path

from . import views

app_name = 'prof'

urlpatterns = [
    path('', views.index, name='index'),
    path('before/', views.before, name='before'),
    path('ing/', views.ing, name='ing'),
    path('after/', views.after, name='after'),
]

audit/StudApp/urls.py
from django.urls import path

from . import views

app_name = 'stud'

urlpatterns = [
    path('', views.index, name='index'),
    path('reg', views.reg, name='reg'),
    path('reg_syl', views.reg_syl, name='reg_syl'),
    path('check', views.check, name='check'),
]

audit/audit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('stud/', include('StudApp.urls')),
    path('prof/', include('ProfApp.urls')),
    path('admin/', admin.site.urls),
]

audit/ProfApp/models.py
from django.db import models

class Prof(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'prof'


class Subject(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50, null=True)
    grade = models.IntegerField(blank=True, null=True)
    prof_id = models.ForeignKey(Prof, models.DO_NOTHING, blank=True, null=True)
    unit_list = models.CharField(max_length=50)

    class Meta:
        managed = True
        db_table = 'subject'


class Unit(models.Model):
    id = models.IntegerField(primary_key=True)
    apply_period = models.DateTimeField(blank=True, null=True)
    limit_num = models.IntegerField(blank=True, null=True)
    audit_type = models.TextField()
    subject = models.ForeignKey(Subject, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'unit'

audit/StudApp/models.py
from django.db import models


class Stud(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    mileage = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'stud'

class Apply(models.Model):
    id = models.AutoField(primary_key=True)
    unit = models.ForeignKey("ProfApp.Unit", on_delete=models.DO_NOTHING, blank=True, null=True)
    student = models.ForeignKey(Stud, on_delete=models.DO_NOTHING, blank=True, null=True)
    admin_mileage = models.IntegerField()
    apply_time = models.DateTimeField()
    remain_semaster = models.IntegerField(blank=True, null=True)
    result = models.BooleanField(blank=True, null=True)
    
    class Meta:
        managed = True
        db_table = 'apply'

class Post(models.Model):
    id = models.IntegerField(primary_key=True)
    subject = models.ForeignKey("ProfApp.Subject", on_delete=models.DO_NOTHING, blank=True, null=True)
    category = models.BooleanField()
    content = models.TextField()
    time = models.DateTimeField()

    class Meta:
        managed = True
        db_table = 'post'

audit/StudApp/forms.py
from django import forms

from StudApp.models import Apply

class BettingForm(forms.ModelForm):
    # admin_mileage = forms.IntegerField(max_value=160)
    # apply_time = forms.DateTimeField

    class Meta:
        model = Apply
        fields = ['admin_mileage']
        labels = {
            'admin_mileage': '마일리지'
        }

audit/ProfApp/views.py
from django.shortcuts import redirect, render
from .models import Subject, Unit

def start_week(unit):
    start_week = []
    unit = unit.replace(" ", "")
    for tar in unit.split(','):
        if '-' in tar: # 유닛인 경우
            bar_index = tar.find('-')
            tar = tar[0:bar_index]
        start_week.append(tar)
    return start_week

def index(request):
    return render(request, 'ProfApp/index.html')

def before(request):
    return render(request, 'ProfApp/class_management_before.html')

def ing(request):
    # 청강관리 눌렀을 때 아래 내용 보여주기
    # 유닛을 입력 받고 이를 저장했을 때 assign id
    if(request.method == "POST"):
        subject = Subject()
        subject.unit_list = request.POST['unit']
        unit_info = subject.unit_list
        # subject.save()
        
        unit = Unit()
        start_week_list = start_week(unit_info)
        # print(start_week_list)
        for sw in start_week_list:
            unit.id = int(sw)
            unit.apply_period = '2022-06-13'
            unit.save()

    # limit_num 추가
    
        return redirect('prof:ing')
        
    return render(request, 'ProfApp/class_management_ing.html')

def after(request):
    return render(request, 'ProfApp/class_management_after.html')

audit/StudApp/views.py
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404

from StudApp.forms import BettingForm
from StudApp.models import Stud

def index(request):
    hong = Stud.objects.get(id=1234567890)
    context = {'mileage': hong.mileage}
    return render(request, 'StudApp/index.html', context)

def reg(request):
    hong = Stud.objects.get(id=1234567890)
    context = {'mileage': hong.mileage}
    return render(request, 'StudApp/desired_class_registration.html', context)

def reg_syl(request):
    hong = Stud.objects.get(id=1234567890)
    apply_num = 2
    if request.method == "POST":
        form = BettingForm(request.POST)
        apply_num += 1 
        if form.is_valid():
            mileage = form.cleaned_data['admin_mileage']
            deducted = hong.mileage - mileage
            hong.mileage = deducted
            hong.save()
            
            # print(mileage)
            Apply = form.save(commit=False)
            Apply.apply_time = timezone.now()
            Apply.student_id = hong.id
            Apply.save()
            context = {'original': hong.mileage, 'apply_num': apply_num}
            return render(request, 'StudApp/desired_class_registration_syllabus.html', context)
        else :
            return redirect('stud:reg_syl')

    else :
        form = BettingForm()
    context = {'form': form, 'original': hong.mileage, 'apply_num': apply_num}
    return render(request, 'StudApp/desired_class_registration_syllabus.html', context)
    # return render(request, 'StudApp/desired_class_registration_syllabus.html')

def check(request):
    hong = Stud.objects.get(id=1234567890)
    context = {'mileage': hong.mileage}
    return render(request, 'StudApp/audit_class_check_.html', context)

audit/ProfApp/templates/ProfApp/index.html
{% load static %}
<h1> 교수/조교 페이지 접속 </h1>
./prof/before <br>
./prof/ing <br>
./prof/after <br>

audit/ProfApp/templates/ProfApp/navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle js-sidebar-toggle">
<i class="hamburger align-self-center"></i>
</a>

<div class= "center"> 주차 별 청강 시스템</div>
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav navbar-align">
        <span class="text-dark"> 현재는 05주차 입니다 </span>
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle" href="#" id="alertsDropdown" data-bs-toggle="dropdown">
                    <div class="position-relative">
                        <i class="align-middle" data-feather="bell"></i>
                        <span class="indicator">1</span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="alertsDropdown">
                    <div class="dropdown-menu-header">
                        4 New Notifications
                    </div>
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="text-danger" data-feather="alert-circle"></i>
                                </div>
                                <div class="col-10">
                                    <div class="text-dark">Update completed</div>
                                    <div class="text-muted small mt-1">Restart server 12 to complete the update.</div>
                                    <div class="text-muted small mt-1">30m ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="text-warning" data-feather="bell"></i>
                                </div>
                                <div class="col-10">
                                    <div class="text-dark">Lorem ipsum</div>
                                    <div class="text-muted small mt-1">Aliquam ex eros, imperdiet vulputate hendrerit et.</div>
                                    <div class="text-muted small mt-1">2h ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="text-primary" data-feather="home"></i>
                                </div>
                                <div class="col-10">
                                    <div class="text-dark">Login from 192.186.1.8</div>
                                    <div class="text-muted small mt-1">5h ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="text-success" data-feather="user-plus"></i>
                                </div>
                                <div class="col-10">
                                    <div class="text-dark">New connection</div>
                                    <div class="text-muted small mt-1">Christina accepted your request.</div>
                                    <div class="text-muted small mt-1">14h ago</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="dropdown-menu-footer">
                        <a href="#" class="text-muted">Show all notifications</a>
                    </div>
                </div>
            </li> 
            <!--
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle" href="#" id="messagesDropdown" data-bs-toggle="dropdown">
                    <div class="position-relative">
                        <i class="align-middle" data-feather="message-square"></i>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="messagesDropdown">
                    <div class="dropdown-menu-header">
                        <div class="position-relative">
                            4 New Messages
                        </div>
                    </div>
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <img src="img/avatars/avatar-5.jpg" class="avatar img-fluid rounded-circle" alt="Vanessa Tucker">
                                </div>
                                <div class="col-10 ps-2">
                                    <div class="text-dark">Vanessa Tucker</div>
                                    <div class="text-muted small mt-1">Nam pretium turpis et arcu. Duis arcu tortor.</div>
                                    <div class="text-muted small mt-1">15m ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <img src="img/avatars/avatar-2.jpg" class="avatar img-fluid rounded-circle" alt="William Harris">
                                </div>
                                <div class="col-10 ps-2">
                                    <div class="text-dark">William Harris</div>
                                    <div class="text-muted small mt-1">Curabitur ligula sapien euismod vitae.</div>
                                    <div class="text-muted small mt-1">2h ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <img src="img/avatars/avatar-4.jpg" class="avatar img-fluid rounded-circle" alt="Christina Mason">
                                </div>
                                <div class="col-10 ps-2">
                                    <div class="text-dark">Christina Mason</div>
                                    <div class="text-muted small mt-1">Pellentesque auctor neque nec urna.</div>
                                    <div class="text-muted small mt-1">4h ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <img src="img/avatars/avatar-3.jpg" class="avatar img-fluid rounded-circle" alt="Sharon Lessman">
                                </div>
                                <div class="col-10 ps-2">
                                    <div class="text-dark">Sharon Lessman</div>
                                    <div class="text-muted small mt-1">Aenean tellus metus, bibendum sed, posuere ac, mattis non.</div>
                                    <div class="text-muted small mt-1">5h ago</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="dropdown-menu-footer">
                        <a href="#" class="text-muted">Show all messages</a>
                    </div>
                </div>
            </li> !-->
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
    <i class="align-middle" data-feather="settings"></i>
  </a>

                <a class="nav-link d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
    <!-- <img src="img/avatars/avatar.jpg" class="avatar img-fluid rounded me-1" alt="Charles Hall" /> --> <span class="text-dark"> Scott Uk-Jin Lee </span>
  </a>
  
                <div class="dropdown-menu dropdown-menu-end">
                    <a class="dropdown-item" href="pages-profile.html"><i class="align-middle me-1" data-feather="user"></i> Profile</a>
                    <a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="pie-chart"></i> Analytics</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="index.html"><i class="align-middle me-1" data-feather="settings"></i> Settings & Privacy</a>
                    <a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="help-circle"></i> Help Center</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Log out</a>
                </div>
            </li>
        </ul>
    </div>

</nav>

audit/ProfApp/templates/ProfApp/sidebar.html
{% load static %}
<nav id="sidebar" class="sidebar js-sidebar">
    <div class="sidebar-content js-simplebar">
        <a class="sidebar-brand" href="index.html">
            <span class="align-middle"><img src="{% static 'ProfApp/img/icons/hy_logo.png' %}" class="avatar img-fluid rounded-circle">  &nbsp; 한양대학교 ERICA </span>
        </a>

    
        <ul class="sidebar-nav">
            <li class="sidebar-header">
                공지 사항
            </li>
            
            <li class="sidebar-item">
                <a class="sidebar-link" href="{% url 'prof:index' %}">
                    <i class="align-middle" data-feather="user"></i> <span class="align-middle">공지 사항</span>
                </a>
            </li>

            <li class="sidebar-header">
                청강 희망
            </li>

            <li class="sidebar-item">
                <a class="sidebar-link" href="{% url 'prof:index' %}">
                    <i class="align-middle" data-feather="square"></i> <span class="align-middle">청강 희망 신청 확인</span>
                </a>
            </li>

            </li>

            <li class="sidebar-header">
                청강 신청
            </li>

            <li class="sidebar-item active">
                <a class="sidebar-link" href="ui-buttons.html">
                    <i class="align-middle" data-feather="square"></i> <span class="align-middle">청강 관리</span>
                </a>
            </li>      
                  
        </ul>    
</nav>

audit/StudApp/templates/StudApp/navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle js-sidebar-toggle">
<i class="hamburger align-self-center"></i>
</a>

<div class= "center"> 주차 별 청강 시스템</div>
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav navbar-align">
            <span class="text-dark"> 현재는 05주차 입니다<br>잔여 마일리지: {{mileage}}점</span>
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle" href="#" id="alertsDropdown" data-bs-toggle="dropdown">
                    <div class="position-relative">
                        <i class="align-middle" data-feather="bell"></i>
                        <span class="indicator">4</span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="alertsDropdown">
                    <div class="dropdown-menu-header">
                        4 New Notifications
                    </div>
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="text-danger" data-feather="alert-circle"></i>
                                </div>
                                <div class="col-10">
                                    <div class="text-dark">Update completed</div>
                                    <div class="text-muted small mt-1">Restart server 12 to complete the update.</div>
                                    <div class="text-muted small mt-1">30m ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="text-warning" data-feather="bell"></i>
                                </div>
                                <div class="col-10">
                                    <div class="text-dark">Lorem ipsum</div>
                                    <div class="text-muted small mt-1">Aliquam ex eros, imperdiet vulputate hendrerit et.</div>
                                    <div class="text-muted small mt-1">2h ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="text-primary" data-feather="home"></i>
                                </div>
                                <div class="col-10">
                                    <div class="text-dark">Login from 192.186.1.8</div>
                                    <div class="text-muted small mt-1">5h ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <i class="text-success" data-feather="user-plus"></i>
                                </div>
                                <div class="col-10">
                                    <div class="text-dark">New connection</div>
                                    <div class="text-muted small mt-1">Christina accepted your request.</div>
                                    <div class="text-muted small mt-1">14h ago</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="dropdown-menu-footer">
                        <a href="#" class="text-muted">Show all notifications</a>
                    </div>
                </div>
            </li> 
            <!--
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle" href="#" id="messagesDropdown" data-bs-toggle="dropdown">
                    <div class="position-relative">
                        <i class="align-middle" data-feather="message-square"></i>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="messagesDropdown">
                    <div class="dropdown-menu-header">
                        <div class="position-relative">
                            4 New Messages
                        </div>
                    </div>
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <img src="img/avatars/avatar-5.jpg" class="avatar img-fluid rounded-circle" alt="Vanessa Tucker">
                                </div>
                                <div class="col-10 ps-2">
                                    <div class="text-dark">Vanessa Tucker</div>
                                    <div class="text-muted small mt-1">Nam pretium turpis et arcu. Duis arcu tortor.</div>
                                    <div class="text-muted small mt-1">15m ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <img src="img/avatars/avatar-2.jpg" class="avatar img-fluid rounded-circle" alt="William Harris">
                                </div>
                                <div class="col-10 ps-2">
                                    <div class="text-dark">William Harris</div>
                                    <div class="text-muted small mt-1">Curabitur ligula sapien euismod vitae.</div>
                                    <div class="text-muted small mt-1">2h ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <img src="img/avatars/avatar-4.jpg" class="avatar img-fluid rounded-circle" alt="Christina Mason">
                                </div>
                                <div class="col-10 ps-2">
                                    <div class="text-dark">Christina Mason</div>
                                    <div class="text-muted small mt-1">Pellentesque auctor neque nec urna.</div>
                                    <div class="text-muted small mt-1">4h ago</div>
                                </div>
                            </div>
                        </a>
                        <a href="#" class="list-group-item">
                            <div class="row g-0 align-items-center">
                                <div class="col-2">
                                    <img src="img/avatars/avatar-3.jpg" class="avatar img-fluid rounded-circle" alt="Sharon Lessman">
                                </div>
                                <div class="col-10 ps-2">
                                    <div class="text-dark">Sharon Lessman</div>
                                    <div class="text-muted small mt-1">Aenean tellus metus, bibendum sed, posuere ac, mattis non.</div>
                                    <div class="text-muted small mt-1">5h ago</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="dropdown-menu-footer">
                        <a href="#" class="text-muted">Show all messages</a>
                    </div>
                </div>
            </li> !-->
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
    <i class="align-middle" data-feather="settings"></i>
  </a>

                <a class="nav-link d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
    <!-- <img src="img/avatars/avatar.jpg" class="avatar img-fluid rounded me-1" alt="Charles Hall" /> --> <span class="text-dark"> 홍길동 </span>
  </a>
  
                <div class="dropdown-menu dropdown-menu-end">
                    <a class="dropdown-item" href="pages-profile.html"><i class="align-middle me-1" data-feather="user"></i> Profile</a>
                    <a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="pie-chart"></i> Analytics</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="index.html"><i class="align-middle me-1" data-feather="settings"></i> Settings & Privacy</a>
                    <a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="help-circle"></i> Help Center</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Log out</a>
                </div>
            </li>
        </ul>
    </div>

</nav>

audit/StudApp/templates/StudApp/sidebar.html
{% load static %}
<nav id="sidebar" class="sidebar js-sidebar">
	<div class="sidebar-content js-simplebar">
		<a class="sidebar-brand" href="{% url 'stud:index' %}">
			<span class="align-middle"><img src="{% static 'StudApp/img/icons/hy_logo.png' %}" class="avatar img-fluid rounded-circle">  &nbsp; 한양대학교 ERICA </span>
		</a>

		<ul class="sidebar-nav">
			<li class="sidebar-header">
				공지 사항
			</li>
			
			<li class="sidebar-item">
				<a class="sidebar-link" href="{% url 'stud:index' %}">
					<i class="align-middle" data-feather="user"></i> <span class="align-middle">공지 사항</span>
				</a>
			</li>

			<li class="sidebar-header">
				청강 희망
			</li>

			<li class="sidebar-item active">
				<a class="sidebar-link" href="{% url 'stud:index' %}">
					<i class="align-middle" data-feather="square"></i> <span class="align-middle">청강 희망 신청</span>
				</a>
			</li>

			<li class="sidebar-item">
				<a class="sidebar-link" href="{% url 'stud:index' %}">
					<i class="align-middle" data-feather="check-square"></i> <span class="align-middle">청강 희망 확인</span>
				</a>
			</li>
	
			</li>

			<li class="sidebar-header">
				청강 신청
			</li>

			<li class="sidebar-item">
				<a class="sidebar-link" href="{% url 'stud:reg' %}">
					<i class="align-middle" data-feather="square"></i> <span class="align-middle">청강 신청</span>
				</a>
			</li>

			<li class="sidebar-item">
				<a class="sidebar-link" href="{% url 'stud:check' %}">
					<i class="align-middle" data-feather="check-square"></i> <span class="align-middle">청강 신청 확인</span>
				</a>
			</li>

			</li>

			<li class="sidebar-header">
				비교과/특강
			</li>

			<li class="sidebar-item">
				<a class="sidebar-link" href="{% url 'stud:index' %}">
					<i class="align-middle" data-feather="grid"></i> <span class="align-middle">비교과/특강 신청</span>
				</a>
			</li>
			
		</ul>
	</div>
</nav>